tpconfig.url: https://tp-q2.dev.intern.nav.no/api/tpconfig

maskinporten.validation:
  environment: DEV
  permit-all: 889640782

VEDTAK_HENDELSE_KAFKA_TOPIC: pensjonsamhandling.sam-vedtak-hendelser-q2
YTELSE_HENDELSE_KAFKA_TOPIC: pensjonsamhandling.tp-hendelser-q2

spring:
  jpa:
    hibernate:
      ddl-auto: update
